# Generated by Django 2.2 on 2019-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name': 'BaseInfo',
            },
        ),
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='edu',
            options={'verbose_name': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='lang',
            options={'verbose_name': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='showblocks',
            options={'verbose_name': 'Blocks'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skills'},
        ),
        migrations.AlterField(
            model_name='achievements',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='edu',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='edu',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='edu',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lang',
            name='quality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lang',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='showblocks',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
