# Generated by Django 2.2 on 2019-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190426_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name': 'BaseInfo', 'verbose_name_plural': 'BaseInfo'},
        ),
        migrations.AlterModelOptions(
            name='edu',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='lang',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='showblocks',
            options={'verbose_name': 'Block', 'verbose_name_plural': 'Blocks'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='career_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='telephone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
